### ISSUE TITLE
Why the Debian images are not being released?

### ISSUE THREAD

**Issue by xr09** [corretto/corretto-docker#100]
I wonder why the Debian images are not being released even though the Dockerfile is here on the repo. I looked on public.ecr.aws but found nothing.

**Comment by yrsurya** [comment]
yeah same here , I tried to find in both public ECR and docker hub didn't find it's that intentional ?

**Comment by xr09** [comment]
It is intentional, everywhere I asked the answer is build it yourself, there are no plans to release the Debian images, only Alpine.
