### ISSUE TITLE
Release debian-based images 

### ISSUE THREAD

**Issue by tinder-ryantrontz** [corretto/corretto-docker#106]
### Is your feature request related to a problem?
There's no "Problem" per se. This is just a question, but this seemed like the most applicable label. 

### Describe a solution you would like
Please provide a clear and concise description of what you want to happen.
I noticed that there are debian-based Dockerfiles in this repo, but the images are referenced in the Readme's "Supported Tags" section, and they don't seem to be available for public consumption. I saw #100 was closed by the reporter without a response from the maintainers. Is there a plan to release debian-based images? 

### Describe alternatives you have considered
Please provide a clear and concise description
of any alternative solutions or features you have considered.
I've considered the following: 
* using alpine linux 
* using eclipse images 
* building my own

**Comment by Rudometov** [comment]
Hi, 
Thanks for your interest in Corretto.

This feature has been requested before [#24](https://github.com/corretto/corretto-docker/issues/24), however the Debian based images are not published by the Corretto team, and we have no plans to publish them at this time. 

You can create your own images from the Dockerfiles in this repository (f.e. [https://github.com/corretto/corretto-docker/blob/main/17/jdk/debian/Dockerfile](https://github.com/corretto/corretto-docker/blob/main/17/jdk/debian/Dockerfile)).
