### ISSUE TITLE
alpine images on Docker Hub

### ISSUE THREAD

**Issue by ijin** [corretto/corretto-docker#12]
I would like to have the alpine images to be hosted on Docker Hub as well. Currently, only Amazon Linux 2 versions are available.

**Comment by nixphix** [comment]
Also versioning the images with an OS base image version would help, like [Python](https://hub.docker.com/_/python) has tags based on OS base image and versions. I can help if maintainers are accepting PRs.

**Comment by davecurrie** [comment]
Hi. Preview images are currently available on Docker Hub from https://hub.docker.com/r/amazoncorretto/alpine-preview.

**Comment by cliveverghese** [comment]
> Also versioning the images with an OS base image version would help, like [Python](https://hub.docker.com/_/python) has tags based on OS base image and versions. I can help if maintainers are accepting PRs.

Please feel free to submit the PR.
