### ISSUE TITLE
Docker images out of date on DockerHub

### ISSUE THREAD

**Issue by mmccarthy404** [corretto/corretto-docker#130]
I'm trying to use the `amazoncorretto:17-al2022-RC-headful` image from DockerHub, which currently seems to be deployed from here: https://github.com/corretto/corretto-docker/blob/7996710c56ef95dba20bb0d5784b0e941dfdaa5b/17/headful/al2022/Dockerfile

However, I noticed a bug where the headless RPM is used instead of the headful one: https://github.com/corretto/corretto-docker/blob/7996710c56ef95dba20bb0d5784b0e941dfdaa5b/17/headful/al2022/Dockerfile#L11

I see you've fixed this in your main branch 2 weeks ago: https://github.com/corretto/corretto-docker/blob/main/17/headful/al2022/Dockerfile#L11

However, the change still isn't reflected in DockerHub, even though it was pushed 9 days ago: 
![image](https://user-images.githubusercontent.com/54035558/209451166-8a2ece4b-8bc8-479b-85f0-05cece6bee4d.png)

This may not be a bug, and just part of your normal DevOps workflow, but I'm curious when these changes will be deployed?

**Comment by lutkerd** [comment]
Thanks for reporting this. We haven't requested the new docker images be built by DockerHub for this. The push you see there is likely from an automated rebuild of our images triggered by an update to the base AmazonLinux image. We will discuss a release timeline internally and these changes may not be made available until the Q1 release on January 17.

**Comment by lutkerd** [comment]
New images have been available for sometime, closing issue.
