### ISSUE TITLE
"latest" should be 17

### ISSUE THREAD

**Issue by uhinze** [corretto/corretto-docker#133]
### Describe the bug
The `latest` tag is currently the same as tags `8`, `8u362`, `8u362-al2`, `8-al2-full`, `8-al2-jdk`. The current LTS version is 17. 

### To Reproduce
Visit https://hub.docker.com/_/amazoncorretto

### Expected behavior
`latest` should point to the latest LTS version.

### Additional context
I'm getting started with Corretto, the above issue confuses me as to which version I should take.

**Comment by Rudometov** [comment]
Thank you for submission. Glad to hear you are starting with Corretto and great that you are considering the latest LTS version which is indeed 17. 
While having latest point to 8 really can bring confusion, changing latest from 8 to 17 would make a sort of hard update for the customers, possibly breaking them, which is something we would like to avoid.
