### ISSUE TITLE
Please consider to remove src.zip from amazoncorretto:x.x.x-alpine images

### ISSUE THREAD

**Issue by armsargis** [corretto/corretto-docker#139]
Please consider possibility to remove src.zip from amazoncorretto:x.x.x-alpine images, I guess its useless to have sources in JDK for runtime environment or probably nice to have another image amazoncorretto:x.x.x-alpine-slim. 

/usr/lib/jvm/java-17-amazon-corretto # ls -lha /usr/lib/jvm/default-jvm/lib/src.zip
-rw-r--r--    1 root     root       49.3M Jan 10 21:49 /usr/lib/jvm/default-jvm/lib/src.zip

it adding additional 50M.

Thanks

**Comment by benty-amzn** [comment]
Hi, thanks for contacting us about this. We agree this would be a good improvement and will look into it for a future release. We'll update this issue when images without src.zip are available.

**Comment by lutkerd** [comment]
Changes have been merged and we will release with the Q3 updates on July 18th.

**Comment by lutkerd** [comment]
Latest AmazonCorretto:xx-alpine images do not have the src.zip.
