### ISSUE TITLE
11.0.8.10 unavailable in docker hub

### ISSUE THREAD

**Issue by Geeman201** [corretto/corretto-docker#14]
Hey,

Noticed the latest commit updates the images to 11.0.8.10 (https://github.com/corretto/corretto-docker/commit/62ad57b8dec957bae1f29975a567cd67cd841d2a) but currently unable to see it in the official [dockerhub](https://hub.docker.com/_/amazoncorretto). 

Any rough timelines on when they will be available?

**Comment by davecurrie** [comment]
Hi. Our Docker official image PR was merged an hour ago -- see https://github.com/docker-library/official-images/pull/8359. It should be available in Docker Hub soon.

**Comment by Geeman201** [comment]
Brilliant👍 thanks for the update
