### ISSUE TITLE
Debian stable corretto images

### ISSUE THREAD

**Issue by anirbanmu** [corretto/corretto-docker#140]
I see that Debian based Dockerfiles exist for Corretto (e.g. https://github.com/corretto/corretto-docker/blob/main/17/slim/debian/Dockerfile) but:
- they don't seem to be published on https://hub.docker.com/_/amazoncorretto
- the image is based on old debian stable, as current stable is `bullseye` -- https://www.debian.org/releases/stable/.

Are there plans to publish these Debian based Corretto images? If so, would you accept a PR to update the Debian dockerfiles to inherit from `debian:stable-slim` rather than `debian:buster-slim` [here](https://github.com/corretto/corretto-docker/blob/main/17/slim/debian/Dockerfile#L1) so that they always follow upstream Debian stable?

**Comment by earthling-amzn** [comment]
Thank you for contacting us. We would welcome a PR, but we have no plans at this time to publish a Debian based image.
