### ISSUE TITLE
Please add tar or unzip executable to allow recent Maven Wrapper usage

### ISSUE THREAD

**Issue by norrisjeremy** [corretto/corretto-docker#141]
The latest [Maven Wrapper](https://maven.apache.org/wrapper/) release (3.2.0) includes a new `only-script` distribution that eliminates the need to download and use the Maven Wrapper jar.

However, this new version requires either a tar or unzip executable to be available in order to extract the Maven distribution, which are not present by default in the `amazoncorretto` docker images.

It would be great if the Amazon team would consider installing either tar or unzip packages by default in the official `amazoncorretto` Docker images so that they would work out of the box with the latest Maven Wrapper release.

### Is your feature request related to a problem?
The latest Maven Wrapper release when used with the `only-script` distribution requires either a tar or unzip executable to be available in order to extract the Maven distribution.

### Describe a solution you would like
Have either the tar or unzip package installed by default in the official Docker images.

### Describe alternatives you have considered
n/a

### Additional context
n/a

**Comment by earthling-amzn** [comment]
Thank you for this request. Unfortunately, we are not going to do this. We intentionally keep these Docker images small to reduce our maintenance load and our vulnerability surface. Please install whatever packages you need into your container.

**Comment by norrisjeremy** [comment]
That's really a shame to hear.
