### ISSUE TITLE
Corretto image tag based on AL2023

### ISSUE THREAD

**Issue by yairkukielkazunzunegui** [corretto/corretto-docker#144]
[Amazon linux 2023](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-linux-2023/) is GA since the 15th of March 2023. 
Will there be a corretto image tag based on al2023? 
Would it be possible to give some timeline for this?

Thank you!

**Comment by lutkerd** [comment]
We are working on this and will have updated images soon.

**Comment by lutkerd** [comment]
Changes have been merged and the images should be available on our [ECR Gallery](https://gallery.ecr.aws/amazoncorretto/amazoncorretto) and [DockerHub](https://hub.docker.com/_/amazoncorretto) in the next few hours.

**Comment by lutkerd** [comment]
I forgot to remove the RC in the tags which will be resolved by https://github.com/corretto/corretto-docker/pull/146 and released early this coming week.

**Comment by yairkukielkazunzunegui** [comment]
Thank you!

**Comment by lutkerd** [comment]
Image without "RC" are published on ECR Gallery and DockerHub.
