### ISSUE TITLE
Image size differences

### ISSUE THREAD

**Issue by yrsurya** [corretto/corretto-docker#15]
I am seeing different image size than what I am seeing in dockerhub

docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
amazoncorretto                  latest              52ca599541e8        6 hours ago         344MB
amazoncorretto/alpine-preview   11-alpine-jre       82cfcce06d61        34 hours ago        134MB
amazoncorretto/alpine-preview   11.0.8-alpine-jre   82cfcce06d61        34 hours ago        134MB
amazoncorretto/alpine-preview   11.0.8-alpine       7347a8c33c1f        34 hours ago        322MB

In dockerhub I am seeing different sizes any issue with my docker version or I am testing this too early?

**Comment by cliveverghese** [comment]
Hi @yrsurya,

Thank you for contacting us. 

The [dockerhub images sizes](https://hub.docker.com/repository/registry-1.docker.io/amazoncorretto/alpine-preview/tags?page=1) are compressed images sizes. Once pulled to the local environment, the `docker images` command shows the uncompressed image size.

**Comment by yrsurya** [comment]
Thanks for reply , even I found that now as there is open issue for long time ago - https://github.com/docker/hub-feedback/issues/331.

Also can you please confirm if above mentioned alpine images are final? i saw AWS announcements but not able to find official corretto-alpine image other than preview one

```Today Amazon Corretto is releasing its July quarterly critical updates. This release also includes Corretto 8 & 11 support for Alpine Linux, Corretto 8 with JFR (JDK Flight Recorder) which can be used with JMC (JDK Mission Control) built for (to support) Corretto, Corretto 11 32bit x86 for Linux and ARM64 optimizations for both Corretto 8 & 11.```

**Comment by jguo11** [comment]
Hi @yrsurya, sorry for the delay in reply. We have recently moved to [amazoncorretto/amazoncorretto](https://hub.docker.com/r/amazoncorretto/amazoncorretto/tags) as official repo for alpine image. We recommend you to switch to that repository. Please let us know if you have further question regarding the size or image.
