### ISSUE TITLE
Provide an alpine 3.18 based image

### ISSUE THREAD

**Issue by JEnglandOhalo** [corretto/corretto-docker#156]
Now that Alpine 3.18 has been released, it would be great to have Corretto docker images based on this new version so that downstream projects can benefit from the upgrades included in this new version of Alpine Linux.

**Comment by rgoltz** [comment]
Hey. Please note that 
* AWS ECR Basic-Scanner/Clair (https://github.com/aws/containers-roadmap/issues/2028) and 
* AWS ECR Enhanced Scanner/Inspector (https://github.com/aws/containers-roadmap/issues/2027) 

does ***not*** support Alpine 3.18 images for vulnerability scans yet. May that might be a blocker for some users to move new release based on Alpine 3.18.

**Comment by lutkerd** [comment]
This will go out with the Q3 release on July 18th.

**Comment by lutkerd** [comment]
Images based on Alpine 3.18 are available on the [Public ECR Gallery](https://gallery.ecr.aws/docker/library/amazoncorretto) and [DockerHub](https://hub.docker.com/_/amazoncorretto)
