### ISSUE TITLE
Alpine images not found in public.ecr.aws

### ISSUE THREAD

**Issue by oussemos** [corretto/corretto-docker#177]
Hi, any reason why alpine images are pushed to docker hub, but not to `public.ecr.aws/amazoncorretto/amazoncorretto` ?

`Image public.ecr.aws/amazoncorretto/amazoncorretto:17-alpine not found in source or destination registries `

Thank you

**Comment by lutkerd** [comment]
The Alpine images are available from `public.ecr.aws/docker/library/amazoncorretto:17-alpine` and are kept up to date there.

**Comment by oussemos** [comment]
Thank you @lutkerd
