### ISSUE TITLE
Update image to use latest Corretto version available

### ISSUE THREAD

**Issue by bszeliga** [corretto/corretto-docker#178]
Thank you for taking the time to help improve Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

If your proposal is specific to Corretto docker images,
then you are in the right place.
Please proceed with the following.

### Is your feature request related to a problem?
Please provide a clear and concise description of what the problem is.

According to Corretto docs - there is a 17.0.8.8-1 version available and the current docker image is still on 17.0.8.7-1.

### Describe a solution you would like
Please provide a clear and concise description of what you want to happen.

Update the Corretto docker image to use the latest Corretto version available.

### Describe alternatives you have considered
Please provide a clear and concise description
of any alternative solutions or features you have considered.

**Comment by bszeliga** [comment]
Upon closer look I see that they are updated - but the actual repositories are still containing 17.0.8.7-1

**Comment by benty-amzn** [comment]
Good catch and thanks for letting us know - [docker-library#15339](https://github.com/docker-library/official-images/pull/15339)
