### ISSUE TITLE
Changelog / update history

### ISSUE THREAD

**Issue by oussemos** [corretto/corretto-docker#18]
Hello,

Do you have any maintained changelog or document hisotry for corretto updates ?

I found this one, but i doesn't look up to date since January https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/doc-history.html

Thank you

**Comment by TianminShi** [comment]
Hi, 
you can find Corretto changelog here:
Corretto11 : https://github.com/corretto/corretto-11/blob/develop/CHANGELOG.md
Corretto8 :  https://github.com/corretto/corretto-8/blob/develop/CHANGELOG.md

**Comment by oussemos** [comment]
Thanks @TianminShi
