### ISSUE TITLE
Provide an alpine 3.19 based image

### ISSUE THREAD

**Issue by jaikanth-arcadia** [corretto/corretto-docker#188]
Thank you for taking the time to help improve Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

If your proposal is specific to Corretto docker images,
then you are in the right place.
Please proceed with the following.

### Is your feature request related to a problem?
No, it's an enhancement

### Describe a solution you would like
Alpine 3.19 has been released, it would be great to have Corretto docker images based on this new version so that downstream projects can benefit from the upgrades included in this new version of Alpine Linux.

### Describe alternatives you have considered
Maintain our own, doesn't benefit the community.

### Additional context
There are some know DNS resolution issues with 3.18 that is solved with 3.19

**Comment by benty-amzn** [comment]
Hi, thanks for reaching out about this and for the PR. We won't publish these images to Dockerhub until our testing and verification process is complete, but we encourage you to build them and test your applications now if you're planning to move to alpine 3.19.  Assuming no blocking bugs are found these should be available on Dockerhub shortly after the 2024-01-16 patch release.

**Comment by ClaudenirFreitas** [comment]
@benty-amzn  it's not related to this issue but... do we have plans to generate the docker tags for the latest java versions e.g [11.0.22.7.1](https://github.com/corretto/corretto-11/releases/tag/11.0.22.7.1) and, [17.0.10.7.1](https://github.com/corretto/corretto-17/releases/tag/17.0.10.7.1)?

**Comment by lutkerd** [comment]
> @benty-amzn it's not related to this issue but... do we have plans to generate the docker tags for the latest java versions e.g [11.0.22.7.1](https://github.com/corretto/corretto-11/releases/tag/11.0.22.7.1) and, [17.0.10.7.1](https://github.com/corretto/corretto-17/releases/tag/17.0.10.7.1)?

Yes, those should go out today.

**Comment by benty-amzn** [comment]
Those updates are on #192.

Resolving this since the alpine 3.19 PR is merged and should be available shortly, along with the new releases.
