### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by bwcxyk** [corretto/corretto-docker#198]
sh: more: command not found
sh: gzip: command not found

There are some basic commands that can't be found, can they be built in.

**Comment by benty-amzn** [comment]
Hi, thanks for contacting us about this
We only modify the base images by adding Corretto to them, as well as any required dependencies.
If there are additional packages you require which are not part of the base image or Corretto, we recommend creating your own docker image using Corretto as a base and installing them using the base image's package manager.

**Comment by bwcxyk** [comment]
ok
