### ISSUE TITLE
Amazon Corretto 22 is not available as an official image on Docker Hub

### ISSUE THREAD

**Issue by fvasco** [corretto/corretto-docker#204]
### Describe the bug
The Corretto 22 announce is wrong.
https://docs.aws.amazon.com/corretto/latest/corretto-22-ug/docker-install.html

### To Reproduce
~~~
docker run amazoncorretto:22 java -version
docker: Error response from daemon: manifest for amazoncorretto:22 not found: manifest unknown: manifest unknown.
~~~

### Expected behavior
~~~
openjdk version "22.0.0" 2024-03-19 
OpenJDK Runtime Environment Corretto-22.0.0.36.2 (build 22.0.0+36-FR)
OpenJDK 64-Bit Server VM Corretto-22.0.0.36.2 (build 22.0.0+36-FR, mixed mode)
~~~

**Comment by benty-amzn** [comment]
Fixed by #206

**Comment by lutkerd** [comment]
Once https://github.com/docker-library/official-images/pull/16525 is merged the tags should be updated within a few hours.

**Comment by chadrako** [comment]
`amazoncorretto:22` docker image is now available. Thank you for bringing this up. Please reach out if you encounter any further issues
