### ISSUE TITLE
Upgrade alpine docker images to alpine 3.20

### ISSUE THREAD

**Issue by edvasqueza** [corretto/corretto-docker#208]
Thank you for taking the time to help improve Corretto.

If your request concerns a security vulnerability then please report it by email to aws-security@amazon.com instead of here.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

If your proposal is specific to Corretto docker images,
then you are in the right place.
Please proceed with the following.

### Is your feature request related to a problem?
No, it's an enhancement.

### Describe a solution you would like
Alpine 3.20 has been released, it would be great to have Corretto docker images based on this new version so that downstream projects can benefit from the upgrades.

### Describe alternatives you have considered
Maintain our own, doesn't benefit the community.

### Additional context
Fixes busybox vulnerabilities and upgrades os packages.

**Comment by benty-amzn** [comment]
Thanks for contacting us about this. We should have a 3.20 Dockerfile available to build preview images soon, and the images should be available on Dockerhub and ECR after the next patch release on 2024-07-15 per https://github.com/corretto/corretto-docker?tab=readme-ov-file#types-of-images-provided

**Comment by TobiX** [comment]
Fixed since 2ba6fded0100fad289ad09f34766fc6b4504a900?
