### ISSUE TITLE
Latest (Java 23) Corretto Dockerfile examples result in build warning.

### ISSUE THREAD

**Issue by brickabaugh-ts** [corretto/corretto-docker#215]
Beginning with the recent release of the Java 23 Corretto alpine docker images, the Dockerfile examples contain an ENV syntax on or about line 19 that results in a warning message during the build of the container image.

The current syntax used in the files is, as follows:

ENV LANG C.UTF-8

The above syntax is consider "legacy", which results in the warning.  Adding an '=' sign between the variable name 'LANG' and the value 'C.UTF-8' resolves the issue, as follows:

ENV LANG=C.UTF-8

The Dockerfile examples released with the Java 22 did not exhibit this issue.

Naturally, this is a minor issue that can be fixed by quickly adding the '=' between the variable name and value.

**Comment by lutkerd** [comment]
Thanks for letting us know. PR to fix all instances of this not just Alpine is https://github.com/corretto/corretto-docker/pull/216

**Comment by lutkerd** [comment]
Fix is merged, we will use these updated images for the next quarterly release on Oct 15.

**Comment by brickabaugh-ts** [comment]
I can confirm that this issue is fixed.
