### ISSUE TITLE
debian images on Docker Hub

### ISSUE THREAD

**Issue by bharatsb** [corretto/corretto-docker#24]
I would like to have the debian images to be hosted on Docker Hub as well. Currently, only Amazon Linux 2 versions are available. Also Dockerfile for debian is not being updated.

**Comment by benty-amzn** [comment]
Hi, thanks for contacting us about this.

This feature has been requested before, and is something we're still looking into.

See [corretto-8-docker#61](https://github.com/corretto/corretto-8-docker/issues/61) for previous discussion.

**Comment by alaa-nassef** [comment]
This is something I'm also interested in

**Comment by missedone** [comment]
looking for debian image as well.

**Comment by narendrareddy527** [comment]
Where can we get the debian image of corretto?

**Comment by benty-amzn** [comment]
The Debian based images are not published by the Corretto team, and we have no plans to publish them at this time. If you want to use them, you are free to create your own images from the Dockerfiles in this repository.
