### ISSUE TITLE
THIRD-PARTY-LICENSES file breaks Atlassian Bitbucket image building

### ISSUE THREAD

**Issue by roneystein** [corretto/corretto-docker#32]
When using amazoncorretto:11.0.8-alpine base image and building a new image using Bitbuckets pipelines the build fails with the message "failed to register layer: Error processing tar file(exit status 1): Container ID 3175151 cannot be mapped to a host ID".

I've tracked the problem to the file:
-rw-r--r--    1 3175151  users        87235 Jul 29 21:53 /licenses/THIRD-PARTY-LICENSES

The file owner should be modified after its installation.

As per Atlassian doc about this issue: [https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-make-your-containers-more-secure-on-Bitbucket/ba-p/998464](https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-make-your-containers-more-secure-on-Bitbucket/ba-p/998464)

### To Reproduce
Use a Bitbucket pipeline to build a Docker image using a Dockerfile that uses the Amazon Corretto image as the base.

### Expected behavior
The image should be built.

### Screenshots
![amz-corretto-image-build-fails](https://user-images.githubusercontent.com/9370944/93612825-60ac1880-f9a6-11ea-88e1-b6c6c28a4261.png)

### Platform information
    Repository: docker hub
    Image tag: amazoncorretto:11.0.8-alpine

**Comment by lutkerd** [comment]
This should be resolved after the docker images are auto-published in the next 24 hours.

**Comment by lutkerd** [comment]
Verified the file ownership in the current amazoncorretto:8u262-alpine and amazoncorretto:11-alpine images, both user and group are root with 0644
