### ISSUE TITLE
Docker Hub Missing Tags for 15

### ISSUE THREAD

**Issue by luketn** [corretto/corretto-docker#33]
### Issue
Whilst the README states that the tags for Corretto 15 are supported, they are not available to pull from either the Docker Hub or ECR registries.
![image](https://user-images.githubusercontent.com/1756555/94629591-9cc86d00-0306-11eb-9e53-af3fbafa717f.png)

### To Reproduce
```
docker pull amazoncorretto:15
```
![image](https://user-images.githubusercontent.com/1756555/94629512-5c68ef00-0306-11eb-805d-5d607a8771c3.png)

### Expected behavior
The supported tags should be published to Docker Hub and ECR.

**Comment by jguo11** [comment]
@luketn Thank you for call out. We will make Corrette 15 available in DockerHub ASAP.

**Comment by jguo11** [comment]
Submitted [PR#8888](https://github.com/docker-library/official-images/pull/8888) to ` docker-library/official-images ` repository.

**Comment by luketn** [comment]
@jguo11 Thanks!

**Comment by luketn** [comment]
Closing as I now see the Corretto 15 tags in DockerHub and can run the image locally and see everything working. Thanks again!
https://hub.docker.com/_/amazoncorretto?tab=tags&page=1&name=15

```
docker run -it --entrypoint /bin/sh  amazoncorretto:15-al2-full
```
![image](https://user-images.githubusercontent.com/1756555/95805881-2ab64600-0d52-11eb-8c8b-7f2a1740c1df.png)
