### ISSUE TITLE
Meaning of tags

### ISSUE THREAD

**Issue by sisivy** [corretto/corretto-docker#52]
Could you please extend the docs?

what is difference between 11-alpine and 11-alpine-full and 11-alpine-jdk?

Cheers

**Comment by dankirkd** [comment]
I think there is no difference.  They are just different tags one can use.

See: https://hub.docker.com/_/amazoncorretto?tab=tags&page=1&ordering=last_updated&name=11-alpine

Pull them down locally and all three have the same Image ID:

9d7de652874a   2021-02-24 12:56:35 -0800 PST   amazoncorretto:11-alpine                                                                               323MB
9d7de652874a   2021-02-24 12:56:35 -0800 PST   amazoncorretto:11-alpine-full                                                                          323MB
9d7de652874a   2021-02-24 12:56:35 -0800 PST   amazoncorretto:11-alpine-jdk                                                                           323MB

**Comment by Constantin07** [comment]
Why not keep just one tag instead of 3 then ? Is there any value in having 3 ?

**Comment by eastig** [comment]
@sisivy Thank you for the questions. We will review it and get back to you.
