### ISSUE TITLE
How to use Chinese in the image?

### ISSUE THREAD

**Issue by xgy560501** [corretto/corretto-docker#6]
How to use Chinese in the image?

**Comment by ziyiluo** [comment]
It's the same as using Chinese characters in other docker images. You just need to set the environment variable `LC_ALL` to `C.UTF-8`:
```bash
# HW.java prints 你好
bash-4.2# java HW
??
bash-4.2# export LC_ALL=C.UTF-8
bash-4.2# java HW
你好
```

Ref: [link](https://github.com/docker-library/php/issues/359#issuecomment-271784228).
