### ISSUE TITLE
Not able to install "tar" in amazoncorretto:8

### ISSUE THREAD

**Issue by ravneetarora** [corretto/corretto-docker#63]
i have a docker file and i am using version 8 as below

FROM amazoncorretto:8.

as part of creating docker image , command to install tar "yum -y install tar" is failing with below errors.

       
Step 10/17 : RUN yum -y install tar
 ---> Running in edcc7dad035e
Loaded plugins: ovl, priorities
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on 
Trying other mirror.
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on 
Trying other mirror.
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on 
Trying other mirror.
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on 
Trying other mirror.
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on 
Trying other mirror.
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on 
Trying other mirror.
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on 
Trying other mirror.

can you please fix

**Comment by lutkerd** [comment]
Thanks for reporting this issue. 

I created a new Dockerfile and tested out building the image and it is working fine for me now (see below). I also checked our repository monitoring and canaries which show no issues with availability. Was the amzn2-core repository that contains the tar package also experiencing issues? You could try disabling the Amazon Corretto repo while installing other packages with `yum install tar --disablerepo AmazonCorretto`, the repo only contains Corretto which is already installed in the image.

```
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM amazoncorretto:8
 ---> 02afee99cdba
Step 2/2 : RUN yum -y install tar
 ---> Running in bb5ebde87bc4
Loaded plugins: ovl, priorities
Resolving Dependencies
--> Running transaction check
---> Package tar.x86_64 2:1.26-35.amzn2 will be installed
--> Finished Dependency Resolution
```

**Comment by ravneetarora** [comment]
> Thanks for reporting this issue.
> 
> I created a new Dockerfile and tested out building the image and it is working fine for me now (see below). I also checked our repository monitoring and canaries which show no issues with availability. Was the amzn2-core repository that contains the tar package also experiencing issues? You could try disabling the Amazon Corretto repo while installing other packages with `yum install tar --disablerepo AmazonCorretto`, the repo only contains Corretto which is already installed in the image.
> 
> ```
> $ docker build .
> Sending build context to Docker daemon  2.048kB
> Step 1/2 : FROM amazoncorretto:8
>  ---> 02afee99cdba
> Step 2/2 : RUN yum -y install tar
>  ---> Running in bb5ebde87bc4
> Loaded plugins: ovl, priorities
> Resolving Dependencies
> --> Running transaction check
> ---> Package tar.x86_64 2:1.26-35.amzn2 will be installed
> --> Finished Dependency Resolution
> ```

Thanks  but i am still encountering the issue.  it was working fine till Friday and Monday(IST) it has started giving me errors

bash-4.2# yum -y install tar --disablerepo AmazonCorretto
Loaded plugins: ovl, priorities
Could not retrieve mirrorlist http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list error was
12: Timeout on http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list: (28, 'Resolving timed out after 5000 milliseconds')


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn2-core/2/x86_64

i can able to curl 8.8.8.8 inside container, so internet will not be an issue. any other area you find it could be a problematic?. I am encountering the issue on 3 machines in region ap-south-1, whereas on 1 machine, it is working(ireland region). is it could be region specific?

**Comment by lutkerd** [comment]
Are you running in a VPC, were there any recent changes? 
What AZ are your instances in?
Any changes to the instances?

Would you be able to provide the output of these commands:
```
dig  amazonlinux.default.amazonaws.com
dig yum.corretto.aws
```

I just launched a new instance in ap-south-1c and was able to update the EC2 instance from amzn2-core and build a docker image that installs tar.

**Comment by ravneetarora** [comment]
yes, it is under VPC, Az:ap-south-1b
no changes done to the instances from my end. I can still confirm from the IT team if they have done any changes.

where do you want me to run these commands? inside container? it wont get dig command

on base machine; base machine as in where i am running container with amazoncorreto image below is the output

; <<>> DiG 9.11.3-1ubuntu1.15-Ubuntu <<>> yum.corretto.aws
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35433
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;yum.corretto.aws.              IN      A

;; ANSWER SECTION:
yum.corretto.aws.       58      IN      A       13.35.129.69
yum.corretto.aws.       58      IN      A       13.35.129.92
yum.corretto.aws.       58      IN      A       13.35.129.110
yum.corretto.aws.       58      IN      A       13.35.129.10

;; Query time: 170 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Jul 19 17:34:40 UTC 2021
;; MSG SIZE  rcvd: 109


ubuntu@ip-10-76-0-23:/var/cache/apt/archives$ dig  amazonlinux.default.amazonaws.com

; <<>> DiG 9.11.3-1ubuntu1.15-Ubuntu <<>> amazonlinux.default.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32459
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;amazonlinux.default.amazonaws.com. IN  A

;; ANSWER SECTION:
amazonlinux.default.amazonaws.com. 898 IN CNAME d21lvh0gtuor4a.cloudfront.net.
d21lvh0gtuor4a.cloudfront.net. 57 IN    A       13.35.129.50
d21lvh0gtuor4a.cloudfront.net. 57 IN    A       13.35.129.122
d21lvh0gtuor4a.cloudfront.net. 57 IN    A       13.35.129.21
d21lvh0gtuor4a.cloudfront.net. 57 IN    A       13.35.129.30

;; Query time: 53 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Mon Jul 19 17:36:15 UTC 2021
;; MSG SIZE  rcvd: 169

**Comment by ravneetarora** [comment]
i checked, simple yum update inside container is also giving the same error

bash-4.2# yum update
Loaded plugins: ovl, priorities
https://yum.corretto.aws/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://yum.corretto.aws/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 5001 milliseconds')
Trying other mirror.

**Comment by lutkerd** [comment]
This is working for me in ap-south-1b as well and I don't see any issues being tracked internally for this. The only differences are that I am using the default VPC with no changes and running on a Ubuntu 20.04.

**Comment by lutkerd** [comment]
The issue seems to be related to your VPC or host configuration. I still do not see any reported issues in the region, our monitoring is not reporting any issues and it worked from another instance in the same AZ.

If you have the VPC flow logs enabled it may show you more info, but that is outside my area of expertise.

**Comment by ravneetarora** [comment]
Thanks Dan. Will check in that area. Thank you for all your help

[cid:c20b0f63-8413-45fc-832a-547b91e5b7de.jpg]
        Ravneet Arora
Staff Engineer
Quark Software Inc.
Email: ***@***.******@***.***>
Direct: +1-303-894-8888<tel:+1-303-894-8888>
Location: India

[cid:SocialLink_Linkedin_32x32_faf38243-e73f-45f9-9151-abc2ed652c9a.png]<https://www.linkedin.com/company/Quark> [cid:SocialLink_Facebook_32x32_bda2aad2-9816-4c5a-abee-dbf8efa4bc2e.png] <https://www.facebook.com/officialQuarkXPress/>  [cid:SocialLink_Twitter_32x32_1c7c4569-2e85-4206-a9e7-e92d746b61c0.png] <https://www.twitter.com/QuarkXPress>  [cid:SocialLink_Youtube_32x32_8efd2a85-8a22-4d68-85ae-4cf423df4fe4.png] <https://www.youtube.com/user/QuarkXPressTV>  [cid:G2_528d8295-781d-4f35-b423-97bcb7e94bbe.jpg] <https://www.g2.com/products/quarkxpress/reviews>



CONFIDENTIALITY NOTICE This e-mail transmission and any documents, files or previous e-mail messages appended or attached to it may be confidential and are intended solely for the use of the individual or entity to whom it is addressed. If you have received this email in error, please notify the sender. To unsubscribe from future emails, please click ***@***.***?Subject=Unsubscribe> and enter "remove' in the body.

**Comment by ravneetarora** [comment]
hi Dan, thank you for all your efforts. it turned out to be DNS issue. we had to give 8.8.8.8 explicitly

**Comment by lutkerd** [comment]
Glad you got it resolved!
