### ISSUE TITLE
8-alpine, 11-alpine do not refer the latest alpine images

### ISSUE THREAD

**Issue by visit1985** [corretto/corretto-docker#76]
`8-alpine`, `8-alpine-full`, `8-alpine-jdk`, `8-alpine-jre` are not referring the latest `8-alpine3.14*` images.

Same for `11-alpine`, `11-alpine-full`, `11-alpine-jdk`, `11-alpine-jre`.

**Comment by daghendrik** [comment]
Alpine 3.15 was released yesterday. Sorry for being impatient, but when do you think 11-alpine reference it @cliveverghese ? :-)

**Comment by JohnPreston** [comment]
> Alpine 3.15 was released yesterday. Sorry for being impatient, but when do you think 11-alpine reference it @cliveverghese ? :-)

I just reset my repo like an idiot (235k dls stats .. gone :boom: ), but I published these on https://gallery.ecr.aws/ews-network/amazoncorretto and they use 3.15 from https://gallery.ecr.aws/docker/library/alpine

Build logs etc. available in the `About` section.

**Comment by rgoltz** [comment]
Dear Corretto-Team,

Thanks a lot for following up on this issue. Please let me point out two things / question:
1) Please not that ECR Image Scan doesn't support Alpine 3.15 yet, please see https://github.com/aws/containers-roadmap/issues/1578 (PR within claircore is already merged, next step would a new clair release, which would be used by AWS ECR). In case you like to scan an image based on Alpine 3.15, it would fail (at the moment).

2) Independently from this current update to Alpine 3.15, what's your steps/strategy on updating the underlaying OS-version and building new images to ECR Public Repo / Dockerhub?
* What's your steps once a new Alpine major version is available (like 3.15 to 3.16)
* In case you using `FROM alpine:3.15` (which would pin the major version), all minor-version (like 3.15.1, 3.15.2, ...) would be used automatically? Or an own Image/Dockerfile/Tag using `FROM alpine:latest` would be a possibility?

Thanks :)

**Comment by cliveverghese** [comment]
> Independently from this current update to Alpine 3.15, what's your steps/strategy on updating the underlaying OS-version and building new images to ECR Public Repo / Dockerhub?
What's your steps once a new Alpine major version is available (like 3.15 to 3.16)

When new alpine versions are released, We would be updating the docker files with a PR similar to #85, and subsequently updating the docker images at [amazoncorretto](https://hub.docker.com/_/amazoncorretto). 

> In case you using FROM alpine:3.15 (which would pin the major version), all minor-version (like 3.15.1, 3.15.2, ...) would be used automatically? Or an own Image/Dockerfile/Tag using FROM alpine:latest would be a possibility?

Yes, all minor versions would be automatically updated. The default alpine tags without an alpine version (`<jdk_version>-alpine, <jdk_version_full>-alpine, <jdk_version>-alpine-full, <jdk_version>-alpine-jdk`) would point to the latest updated alpine version once the above mentioned steps are completed.

**Comment by cliveverghese** [comment]
The default [tags for Corretto 8,11 and 17](https://hub.docker.com/_/amazoncorretto) refer to the alpine version 3.15. Resolving this issue.
