### ISSUE TITLE
No Corretto 17.0.1 for all tags

### ISSUE THREAD

**Issue by luneo7** [corretto/corretto-docker#79]
### Describe the bug
The docker images for 17 were updated for AL and Alpine JDK, but weren't for Debian and Slim. Also the images in docker hub are still only 17.0.0, there are no tags there for 17.0.1

**Comment by TianminShi** [comment]
Hi @luneo7 , tag [17.0.1](https://hub.docker.com/_/amazoncorretto?tab=tags&page=1&name=17.0.1) is available now on docker hub. however I don't think we provide images for Debain or Slim on docker hub(see: https://github.com/docker-library/official-images/blob/master/library/amazoncorretto). So no image for Debain and Slim is expected.
