### ISSUE TITLE
If yum update is run against JAVA 17 latest docker image it move it to a different place

### ISSUE THREAD

**Issue by luneo7** [corretto/corretto-docker#88]
### Describe the bug
If you run `yum update` in the Corretto 17 docker image it will move it to a different folder and you wont be able to use the JAVA_HOME env variable, this broke a lot of our systems.

### To Reproduce

```
$ docker pull docker.io/amazoncorretto:17

$ docker run -it docker.io/library/amazoncorretto:17 /bin/bash

bash-4.2# yum update

bash-4.2# cd $JAVA_HOME

bash: cd: /usr/lib/jvm/java-17-amazon-corretto: No such file or directory

bash-4.2# cd /usr/lib/jvm
bash-4.2# ls
java-17-amazon-corretto.x86_64	jre  jre-17  jre-17-openjdk  jre-openjdk
```

### Expected behavior
It should work as expected

**Comment by luneo7** [comment]
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/8834774/145623897-e85a1529-4711-4293-9bf5-1224aab77d57.png">


<img width="847" alt="image" src="https://user-images.githubusercontent.com/8834774/145623940-001f6644-3184-4809-b37f-9540240b2422.png">

<img width="878" alt="image" src="https://user-images.githubusercontent.com/8834774/145623981-9dede555-b1c4-4283-adbc-a6419599e4b9.png">


<img width="803" alt="image" src="https://user-images.githubusercontent.com/8834774/145624008-00fbb748-872f-4a6e-8c43-6a04ad8562e9.png">

**Comment by benty-amzn** [comment]
Hi, thanks for contacting us about this. We've confirmed that we are able to reproduce the issue and are working on a fix.

**Comment by hubick** [comment]
I'm using the `tomcat:jdk8-corretto-al2` image based on `amazoncorretto:8-al2-jdk`, and after running a `yum update` which currently upgrades to `java-1.8.0-amazon-corretto.x86_64 1:1.8.0_342.b07-4.amzn2` I'm suffering this same issue, where `JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto` but it's located in `/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64`, which means Tomcat now fails to start. Has this regressed again?

**Comment by lutkerd** [comment]
Hi @hubick, I wasn't able to reproduce that behavior with the latest `tomcat:jdk8-corretto-al2`. What is the digest of the image you are using and what is in each of the files under /etc/yum.repos.d/?

**Comment by hubick** [comment]
Hi @lutkerd, sorry, I didn't realize I'd need to be that specific about the tomcat image, but our app's image is derived `FROM tomcat:7.0.103-jdk8-corretto`. Does that help?

**Comment by lutkerd** [comment]
Thanks @hubick! That base image is over 2 years old and does not contain our fix for the issue, there is no priority set on the repository.

```
# docker run -it tomcat:7.0.103-jdk8-corretto /bin/bash
# cat /etc/yum.repos.d/corretto.repo 
[AmazonCorretto]
name=Amazon Corretto
baseurl=https://yum.corretto.aws/$basearch
enabled=1
gpgkey=https://yum.corretto.aws/corretto.key
gpgcheck=1
```

You can either upgrade to a newer tomcat image or add the priority yourself if upgrading is not possible.

**Comment by LOGANBLUE1** [comment]
I had the same issuse while running corretto image
