### ISSUE TITLE
Java 18

### ISSUE THREAD

**Issue by DennisRippinger** [corretto/corretto-docker#94]
Please provide a Java 18 Version of Corretto.

**Comment by lutkerd** [comment]
Thanks for reporting this, we are working on getting Corretto18 Docker images out soon.

**Comment by lutkerd** [comment]
Docker Library PR https://github.com/docker-library/official-images/pull/12193

**Comment by benty-amzn** [comment]
Docker Library PR has been merged and images should be available shortly.

**Comment by lutkerd** [comment]
Images are available on [DockerHub](https://hub.docker.com/_/amazoncorretto), the [AmazonCorretto ECR Gallery](https://gallery.ecr.aws/amazoncorretto/amazoncorretto) and the [mirror of the DockerHub](https://gallery.ecr.aws/docker/library/amazoncorretto) library on ECR.
