### ISSUE TITLE
Java 17  ALAS2-2022-1791

### ISSUE THREAD

**Issue by codingtim** [corretto/corretto-docker#97]
Hi, 

The latest al2 corretto 17 images use corretto version 1:17.0.3.6-1 from https://yum.corretto.aws/corretto.repo
ECR image scan now reports that the container contains the following HIGH vulnerability [ALAS2-2022-1791](https://alas.aws.amazon.com/AL2/ALAS-2022-1791.html) for package java-17-amazon-corretto-devel:1:17.0.3.6-1

According to ALAS-2022-1791 the impacted java 17 version is 17.0.2
and a fix is contained in package java-17-amazon-corretto-devel-17.0.3+6-1.amzn2.1.x86_64

So to me this seems like a false positive? The package version matches the safe package version and there is no newer java 17.0.3 available to upgrade to.
If I should report this somewhere else please feel free to direct me to the correct place.

**Comment by earthling-amzn** [comment]
Apologies for the delayed response. We are looking into the issue.

**Comment by earthling-amzn** [comment]
I'm closing this while we investigate. In the future, please reach out to [security@amazon.com](mailto:security@amazon.com) for security related matters.
